### ISSUE TITLE
NoSuchElementException in Anvil.render()

### ISSUE THREAD

**Issue by danhawkes** [anvil-ui/anvil#119]
Running version `0.5.2`:

```
java.util.NoSuchElementException
    at java.util.ArrayDeque.removeFirst(ArrayDeque.java:263)
    at java.util.ArrayDeque.pop(ArrayDeque.java:498)
    at trikita.anvil.Anvil$Mount$Iterator.end(Anvil.java:319)
    at trikita.anvil.Anvil.render(Anvil.java:228)
    at trikita.anvil.Anvil.render(Anvil.java:142)
    at trikita.anvil.BaseDSL$ItemSelectedWrapper.onItemSelected(BaseDSL.java:482)
    at android.widget.AdapterView.fireOnSelected(AdapterView.java:931)
    at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:920)
    at android.widget.AdapterView.-wrap1(AdapterView.java)
    at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:890)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6126)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by zserge** [comment]
@danhawkes Can you please provide a bit more context? What kind of layout is causing this?

**Comment by danhawkes** [comment]
It's a two-way bound spinner field, something like this:

```
<T> void twoWayBoundSpinner(TypedAdapter<T> adapter, @Nullable T item, Action1<T> onChangedListener) {

  spinner(() -> {
      init(() -> {
          adapter(adapter);
          onItemSelected((adapterView, view, i, l) -> onChangedListener.call(adapter.getItem(i)));
      });
      int index = item != null ? adapter.getItems().indexOf(item) : -1;
      selection(index);
  });
}
```

I believe it's caused by a race condition, as I can select an item from the spinner successfully several times, but occasionally the error occurs. Note all calls to render and happening on the main thread.

**Comment by niltonvasques** [comment]
I got the same error here when I use Anvil.render(this) inside my onStateChanged method from a RenderableView with a recycler view.

```kotlin
class CustomView(context: Context : RenderableView(context)) {
  fun onStateChanged(state: AppState) {
    state = state
    Anvil.render(this)
  }

  override fun view() {
       RecyclerViewDSL7.recyclerView {
          init { 
               // setup adapters 
          }
        }
  }
}```
